/**
 * Nederlandse Digitale Dienst Progress Bar Component (Lit + TypeScript)
 *
 * Exports both NLDDProgressBar and NLDDProgressBarSegment.
 *
 * A progress bar that supports a single value (loading-style) or
 * multiple segments (multi-stage progress, or distribution like
 * storage usage). The consumer provides raw values; the component
 * computes percentages from `max`.
 *
 * Two modes:
 * - `progress` (default): segments sum towards `max`; remaining space
 *   is empty track. ARIA reads "X% voltooid".
 * - `distribution`: segments fill the bar; ARIA enumerates segments.
 *
 * If the sum of segment values exceeds `max`, segments are normalised
 * proportionally to fit and a warning is logged.
 *
 * @element nldd-progress-bar
 *
 * @attr {'progress'|'distribution'} mode - Semantics for ARIA and visualisation (default: 'progress')
 * @attr {number}  max               - Total value (default: 100)
 * @attr {number}  value             - Single-segment shorthand (ignored when segment children are present)
 * @attr {string}  color             - Color for the single-segment shorthand (default: 'accent')
 * @attr {'sm'|'md'|'lg'} size       - Height of the bar (default: 'md')
 * @attr {string}  text              - Label above the bar (left)
 * @attr {'percentage'|'absolute'|'fraction'|'none'} value-format - Format for the value at the top right (default: 'percentage')
 * @attr {string}  value-text        - Full override of the displayed value
 * @attr {string}  accessible-label  - Full override of aria-valuetext
 * @attr {boolean} indeterminate     - Shows a sliding indicator animation (only without segments)
 * @attr {object}  translations      - Override translation keys; unset keys fall back to Dutch
 *
 * @slot - Place for nldd-progress-bar-segment elements
 *
 * @element nldd-progress-bar-segment
 *
 * @attr {number}  value         - Share of the parent's total (default 0; <=0 hides segment)
 * @attr {string}  color         - Color. Semantic (neutral, accent, success, warning, critical) or a Rijkskleur. Default 'accent'.
 * @attr {string}  name          - Name for screenreader text (optional)
 * @attr {string}  tooltip-text  - Override of the auto-generated tooltip text
 */
import { LitElement, html } from 'lit';
import { customElement, property, state } from 'lit/decorators.js';
import { progressBarStyles, progressBarSegmentStyles } from './progress-bar.styles.js';
import { progressBarTemplate } from './progress-bar.template.js';
import { nlddProgressBarTranslations } from './progress-bar.i18n.js';
import type { NLDDProgressBarTranslations } from './progress-bar.i18n.js';
import '../../content/tooltip/tooltip.js';

export type ProgressBarMode = 'progress' | 'distribution';
export type ProgressBarSize = 'sm' | 'md' | 'lg';
export type ProgressBarValueFormat = 'percentage' | 'absolute' | 'fraction' | 'none';

export type ProgressBarColor =
	| 'neutral' | 'accent' | 'success' | 'warning' | 'critical'
	| 'coolgray'
	| 'lintblauw' | 'donkerblauw' | 'hemelblauw' | 'lichtblauw'
	| 'paars' | 'violet'
	| 'robijnrood' | 'roze' | 'rood' | 'oranje'
	| 'donkergeel' | 'geel'
	| 'donkerbruin' | 'bruin'
	| 'donkergroen' | 'groen' | 'mosgroen' | 'mintgroen';


// # nldd-progress-bar-segment

@customElement('nldd-progress-bar-segment')
export class NLDDProgressBarSegment extends LitElement {
	static override styles = progressBarSegmentStyles;

	@property({ type: Number, reflect: true })
	value = 0;

	@property({ type: String, reflect: true })
	color: ProgressBarColor = 'accent';

	@property({ type: String, reflect: true })
	name = '';

	/** Tooltip text override. By default, this is generated by the parent based on
	 *  value-format and the segment `name`. Set explicitly for custom text,
	 *  for example with distribution that has units ("200 GB of 500 GB"). */
	@property({ type: String, reflect: true, attribute: 'tooltip-text' })
	tooltipText = '';

	/** Set by the parent based on value-format. Not for external use —
	 *  consumers use `tooltip-text`. */
	@property({ type: String, attribute: 'data-tooltip-text' })
	dataTooltipText = '';

	get _effectiveTooltip(): string {
		return this.tooltipText || this.dataTooltipText || '';
	}

	override render() {
		const text = this._effectiveTooltip;
		// Only render the tooltip wrapper when there's actual text — avoids
		// mounting an inert nldd-tooltip element with timing="never".
		if (!text) {
			return html`<span class="progress-bar-segment__hover-area"></span>`;
		}
		return html`
			<nldd-tooltip text=${text} timing="instant">
				<span class="progress-bar-segment__hover-area"></span>
			</nldd-tooltip>
		`;
	}
}


// # nldd-progress-bar

@customElement('nldd-progress-bar')
export class NLDDProgressBar extends LitElement {
	static override styles = progressBarStyles;

	@property({ type: String, reflect: true })
	mode: ProgressBarMode = 'progress';

	@property({ type: Number, reflect: true })
	max = 100;

	@property({ type: Number, reflect: true })
	value: number | null = null;

	@property({ type: String, reflect: true })
	color: ProgressBarColor = 'accent';

	@property({ type: String, reflect: true })
	size: ProgressBarSize = 'md';

	@property({ type: String, reflect: true })
	text = '';

	@property({ type: String, reflect: true, attribute: 'value-format' })
	valueFormat: ProgressBarValueFormat = 'percentage';

	@property({ type: String, reflect: true, attribute: 'value-text' })
	valueText = '';

	@property({ type: String, reflect: true, attribute: 'accessible-label' })
	accessibleLabel = '';

	@property({ type: Boolean, reflect: true })
	indeterminate = false;

	/** Override one or more translation keys. Unspecified keys fall back to Dutch. */
	@property({ type: Object })
	translations: Partial<NLDDProgressBarTranslations> = {};

	@state()
	private _segments: NLDDProgressBarSegment[] = [];

	/** True for 500ms after indeterminate=true→false: indicator fades out while
	 *  the segment grows from 0 to its target value. */
	@state()
	private _indeterminateExiting = false;

	/** True for 500ms after indeterminate=false→true: indicator fades in while
	 *  the segment shrinks from its current width to 0. */
	@state()
	private _indeterminateEntering = false;

	private _exitTimeout?: ReturnType<typeof setTimeout>;
	private _enterTimeout?: ReturnType<typeof setTimeout>;

	public _t(key: keyof NLDDProgressBarTranslations): string {
		return this.translations[key] ?? nlddProgressBarTranslations[key];
	}

	/** Returns true when the user has provided segment children. */
	get _hasSegments(): boolean {
		return this._segments.length > 0;
	}

	/** Sum of all segment values, or the parent's own value, or 0. */
	get _totalValue(): number {
		if (this._hasSegments) {
			return this._segments.reduce((sum, s) => sum + Math.max(0, s.value), 0);
		}
		return Math.max(0, this.value ?? 0);
	}

	/** Percentage filled (0–100). */
	get _percentage(): number {
		if (this.max <= 0) return 0;
		return Math.min(100, (this._totalValue / this.max) * 100);
	}

	/** Formatted value string for the header. */
	get _displayValue(): string {
		if (this.valueText) return this.valueText;
		if (this.indeterminate) return '';
		const total = this._totalValue;
		switch (this.valueFormat) {
			case 'none': return '';
			case 'absolute': return `${total}`;
			case 'fraction': return `${total} / ${this.max}`;
			case 'percentage':
			default: return `${Math.round(this._percentage)}%`;
		}
	}

	/** Computed aria-valuetext, unless overridden. */
	get _ariaValueText(): string {
		if (this.accessibleLabel) return this.accessibleLabel;
		if (this.indeterminate) return this._t('components.progress-bar.loading-text');

		const completedSuffix = this._t('components.progress-bar.completed-suffix-text');
		const totalPrefix = this._t('components.progress-bar.total-prefix-text');

		// Single-segment case
		if (!this._hasSegments) {
			return `${Math.round(this._percentage)}% ${completedSuffix}`;
		}

		// Multi-segment
		const named = this._segments.filter(s => s.name);
		const allNamed = named.length === this._segments.length && this._segments.length > 0;
		const segmentDescriptions = this._segments
			.filter(s => s.value > 0)
			.map(s => {
				const pct = this.max > 0 ? Math.round((s.value / this.max) * 100) : 0;
				return s.name ? `${s.name}: ${pct}%` : `${pct}%`;
			});

		if (this.mode === 'distribution') {
			return segmentDescriptions.join(', ');
		}

		// Progress mode
		const totalPct = Math.round(this._percentage);
		if (allNamed) {
			return `${segmentDescriptions.join(', ')}. ${totalPrefix} ${totalPct}% ${completedSuffix}.`;
		}
		return `${totalPct}% ${completedSuffix}`;
	}

	/** True when the header is rendered. Header only shows when `text` is set;
	 *  used to suppress redundant auto-tooltips on single-segment bars. */
	get _hasHeader(): boolean {
		return !!this.text;
	}

	private _attributeObserver?: MutationObserver;

	override firstUpdated(): void {
		this._syncSegments();
	}

	override willUpdate(changed: Map<string, unknown>): void {
		// Detection before render: this way the indicator/segment stays mounted
		// during a flip and the CSS animations can actually run (otherwise the
		// indicator would unmount + remount first, and transitions/animations
		// don't run on a freshly mounted element). The `_begin*` methods cancel
		// the opposite phase themselves, so rapid toggles leave no stale state.
		if (changed.has('indeterminate')) {
			const previous = changed.get('indeterminate');
			if (previous === true && !this.indeterminate) {
				this._beginIndeterminateExit();
			} else if (previous === false && this.indeterminate) {
				this._beginIndeterminateEnter();
			}
		}
	}

	override updated(): void {
		// Sync on any update — cheap, and properties like text/valueText also
		// affect tooltip suppression (single-segment + header).
		this._syncSegments();
	}

	/** Indicator fades out, segment grows from 0 to its target — both 500ms. */
	private _beginIndeterminateExit(): void {
		this._cancelIndeterminateEnter();
		this._indeterminateExiting = true;
		this._exitTimeout = setTimeout(() => {
			this._indeterminateExiting = false;
			this._exitTimeout = undefined;
		}, 500);
	}

	/** Indicator fades in, segment shrinks from current width to 0 — both 500ms. */
	private _beginIndeterminateEnter(): void {
		this._cancelIndeterminateExit();
		this._indeterminateEntering = true;
		this._enterTimeout = setTimeout(() => {
			this._indeterminateEntering = false;
			this._enterTimeout = undefined;
		}, 500);
	}

	private _cancelIndeterminateExit(): void {
		if (this._exitTimeout) {
			clearTimeout(this._exitTimeout);
			this._exitTimeout = undefined;
		}
		this._indeterminateExiting = false;
	}

	private _cancelIndeterminateEnter(): void {
		if (this._enterTimeout) {
			clearTimeout(this._enterTimeout);
			this._enterTimeout = undefined;
		}
		this._indeterminateEntering = false;
	}

	/** Auto-tooltip based on parent's value-format. Override via segment.tooltip. */
	private _formatSegmentTooltip(seg: NLDDProgressBarSegment): string {
		const v = Math.max(0, seg.value);
		const pct = this.max > 0 ? Math.round((v / this.max) * 100) : 0;
		let valuePart: string;
		switch (this.valueFormat) {
			case 'absolute': valuePart = `${v}`; break;
			case 'fraction': valuePart = `${v} / ${this.max}`; break;
			case 'percentage':
			case 'none':
			default: valuePart = `${pct}%`; break;
		}
		return seg.name ? `${seg.name}: ${valuePart}` : valuePart;
	}

	override disconnectedCallback(): void {
		super.disconnectedCallback();
		this._cancelIndeterminateExit();
		this._cancelIndeterminateEnter();
		this._attributeObserver?.disconnect();
	}

	private _onSlotChange(): void {
		const slot = this.shadowRoot?.querySelector<HTMLSlotElement>('slot:not([name])');
		const assigned = slot?.assignedElements({ flatten: true }) ?? [];
		this._segments = assigned.filter(
			(el): el is NLDDProgressBarSegment => el.tagName === 'NLDD-PROGRESS-BAR-SEGMENT',
		);

		// Re-observe each segment for value/color/name/tooltip changes so the
		// parent re-computes widths and ARIA when a child attribute mutates.
		this._attributeObserver?.disconnect();
		this._attributeObserver = new MutationObserver(() => {
			this.requestUpdate();
			this._syncSegments();
		});
		for (const seg of this._segments) {
			this._attributeObserver.observe(seg, {
				attributes: true,
				attributeFilter: ['value', 'color', 'name', 'tooltip-text'],
			});
		}

		this._syncSegments();
	}

	private _syncSegments(): void {
		// Compute per-segment widths. If sum exceeds max, normalise.
		const total = this._totalValue;
		const denominator = total > this.max ? total : this.max;

		if (total > this.max && this._hasSegments) {
			// eslint-disable-next-line no-console
			console.warn(
				`[nldd-progress-bar] Sum of segment values (${total}) exceeds max (${this.max}). ` +
				'Segments are normalised proportionally.',
			);
		}

		// Unified path for slotted and internal segments. The internal segment
		// lives in shadow DOM and is rendered by the template when there are no
		// slotted children — both share the same dynamic-attribute logic here.
		const internalSegment = this.shadowRoot?.querySelector<NLDDProgressBarSegment>(
			'.progress-bar__segment',
		) ?? null;
		const allSegments: NLDDProgressBarSegment[] = internalSegment
			? [internalSegment, ...this._segments]
			: [...this._segments];

		// Suppress redundant auto-tooltip when there's only one visible segment
		// and the header already shows the same value. The user's explicit
		// `tooltip-text` attribute still triggers a tooltip.
		const visibleCount = allSegments.filter(s => Math.max(0, s.value) > 0).length;
		const suppressAutoTooltip = visibleCount <= 1 && this._hasHeader;

		const isExiting = this._indeterminateExiting;
		const isEntering = this._indeterminateEntering;

		for (const seg of allSegments) {
			const v = Math.max(0, seg.value);
			if (v <= 0) {
				seg.hidden = true;
				seg.removeAttribute('data-mode');
				seg.dataTooltipText = '';
				continue;
			}
			seg.hidden = false;
			const pct = denominator > 0 ? (v / denominator) * 100 : 0;
			seg.style.setProperty('--context-progress-bar-segment-width', `${pct}%`);
			// Progress mode: each segment a capsule. Distribution mode:
			// segments are rectangular, only the track's outer corners are
			// rounded (via overflow:hidden + border-radius on the track).
			seg.setAttribute('data-mode', this.mode);
			seg.dataTooltipText = suppressAutoTooltip ? '' : this._formatSegmentTooltip(seg);
			seg.toggleAttribute('data-grow', isExiting);
			seg.toggleAttribute('data-shrink', isEntering);
		}
	}

	private _onSlotChangeBound = this._onSlotChange.bind(this);

	override render() {
		return progressBarTemplate(this, this._onSlotChangeBound);
	}
}

declare global {
	interface HTMLElementTagNameMap {
		'nldd-progress-bar': NLDDProgressBar;
		'nldd-progress-bar-segment': NLDDProgressBarSegment;
	}
}
