/**
 * Generates a static logo module from logo.svg.
 * This replaces the Vite-specific ?raw import so that
 * nldd-top-navigation-bar works with both Vite and plain tsc.
 *
 * Output: src/components/navigation/top-navigation-bar/logo.ts
 */

import { readFileSync, writeFileSync } from 'node:fs';
import { resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const svgPath = resolve(__dirname, '../src/components/navigation/top-navigation-bar/logo.svg');
const outputPath = resolve(__dirname, '../src/components/navigation/top-navigation-bar/logo.ts');

const svg = readFileSync(svgPath, 'utf-8').trim();

const output = `// Auto-generated by scripts/generate-logo.js — do not edit manually.

export default ${JSON.stringify(svg)};
`;

writeFileSync(outputPath, output, 'utf-8');
console.log(`Generated logo module → ${outputPath}`);
